### ISSUE TITLE
Infinite loop on no rating change

### ISSUE THREAD

**Issue by praran26** [vedangmehta/codeforces-rating-alert#1]
If in some contest, the rating does not change, the while loop will continue forever. Thus, the script will not notify that ratings have been updated (although for the given handle, its +0).

**Comment by vedangmehta** [comment]
I've found a way to fix this. I'll fix the issue soon.

**Comment by vedangmehta** [comment]
Fixed the issue :)

**Comment by praran26** [comment]
Looks good. :)
